swagger: "2.0"
info:
  title: Sunglasses.io API
  description: For all your sunglass store needs
  version: "1.0.0"
# the domain of the service
host: "localhost:3001"
# array of all schemes that your API supports
schemes:
  - https
# will be prefixed to all paths
basePath: /v1
produces:
  - application/json
paths:
  /brands:
    get:
      summary: List of Brands
      description: |
        The Brands endpoint returns information about all available brands in
        the database. The response includes a brand id and name.
        proper display order.
      parameters:
        - name: query
          in: query
          description: Causes return array to only contain Brands that have a name match
          required: false
          type: string
      tags:
        - Brands
      responses:
        200:
          description: An array of brands
          schema:
            type: array
            items:
              $ref: "#/definitions/Brand"
  /products:
    get:
      summary: List of Products
      description: |
        The Products endpoint returns information about all available products in        the database. The response includes a prodct id, name, price, and description. Also inclues a linking id to a Brand as well as an array of images to use with the product.
      parameters:
        - name: query
          in: query
          description: Causes return array to only contain Products that have a name match
          required: false
          type: string
      tags:
        - Products
      responses:
        200:
          description: An array of Products
          schema:
            type: array
            items:
              $ref: "#/definitions/Product"
definitions:
  Brand:
    type: object
    properties:
      id:
        type: string
        description: Unique identifier representing a specific brand.
      name:
        type: string
        description: Name of the brand.
  Product:
    type: object
    properties:
      id:
        type: string
        description: Unique identifier representing a specific product.
      categoryId:
        type: string
        description: Identifier linking this product to a category.
      name:
        type: string
        description: Name of the product.
      description:
        type: string
        description: Description about this product
      price:
        type: number
        description: Price for this product
      imageUrls:
        type: array
        items:
          type: string
        description: Array of image Urls for this product
